-- Add missing tables: DOCUMENTS, INTERACTIONS, TRACKED_ASSETS, ORG_MEMBERSHIPS
-- Run this in Snowflake to complete the schema
-- Date: 2025-01-27

USE WAREHOUSE COMPUTE_WH;  -- Update with your warehouse name if different
USE DATABASE THIRDEYE_DEV;
USE SCHEMA PUBLIC;

-- Documents Table (no foreign key to avoid FK errors)
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.DOCUMENTS (
    DOC_ID VARCHAR(500) PRIMARY KEY,
    ORG_ID VARCHAR(36),
    TITLE VARCHAR(500) NOT NULL,
    GOOGLE_DOC VARIANT,
    CONFUSION_DENSITY FLOAT,
    TOTAL_TRIGGERS INTEGER DEFAULT 0,
    USERS_AFFECTED INTEGER DEFAULT 0,
    CONTENT TEXT,
    HOTSPOTS VARIANT,
    LAST_ANALYZED TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ORG_ID, DOC_ID);

-- Interactions Table (no foreign keys to avoid FK errors)
-- Note: Foreign key constraints removed - application code will enforce referential integrity
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.INTERACTIONS (
    INTERACTION_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36),
    DOC_ID VARCHAR(500),
    ANCHOR_ID VARCHAR(255),
    CONTENT TEXT,
    GAP_HYPOTHESIS VARIANT,
    EXPLANATION_GIVEN VARIANT,
    USER_FEEDBACK VARCHAR(50),
    READING_STATE VARCHAR(20),
    DWELL_TIME_MS INTEGER,
    CONCEPTS VARIANT,
    TELEMETRY VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (USER_ID, CREATED_AT);

-- Tracked Assets Table (general asset tracking for documents, GitHub repos, etc.)
-- Note: Snowflake doesn't support CREATE INDEX on standard tables
-- The CLUSTER BY clause provides automatic optimization instead
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.TRACKED_ASSETS (
    ASSET_ID VARCHAR(500) PRIMARY KEY,
    ORG_ID VARCHAR(36),
    ASSET_TYPE VARCHAR(50) NOT NULL,  -- 'GOOGLE_DOC', 'GITHUB', 'NOTION', 'CONFLUENCE', etc.
    TITLE VARCHAR(500) NOT NULL,
    GOOGLE_DOC VARIANT,
    CONFUSION_DENSITY FLOAT,
    TOTAL_TRIGGERS INTEGER DEFAULT 0,
    USERS_AFFECTED INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ORG_ID, ASSET_TYPE);

-- Organization Memberships Table
-- Note: Foreign key constraints removed - application code will enforce referential integrity
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.ORG_MEMBERSHIPS (
    MEMBERSHIP_ID VARCHAR(36) PRIMARY KEY,
    ORG_ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    ROLE VARCHAR(20) NOT NULL DEFAULT 'member',  -- 'admin' | 'member'
    JOINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE(ORG_ID, USER_ID)
)
CLUSTER BY (ORG_ID, USER_ID);

-- Verify all tables were created
SELECT 'DOCUMENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM THIRDEYE_DEV.PUBLIC.DOCUMENTS
UNION ALL
SELECT 'INTERACTIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM THIRDEYE_DEV.PUBLIC.INTERACTIONS
UNION ALL
SELECT 'TRACKED_ASSETS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM THIRDEYE_DEV.PUBLIC.TRACKED_ASSETS
UNION ALL
SELECT 'ORG_MEMBERSHIPS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM THIRDEYE_DEV.PUBLIC.ORG_MEMBERSHIPS;
