-- Add WHITELISTED_FOLDERS table for enterprise document detection
-- Run this in Snowflake to enable whitelisting
-- Date: 2025-02-08

USE WAREHOUSE COMPUTE_WH;
USE DATABASE THIRDEYE_DEV;
USE SCHEMA PUBLIC;

-- Whitelisted Folders Table
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.WHITELISTED_FOLDERS (
    FOLDER_ID VARCHAR(36) PRIMARY KEY,
    ORG_ID VARCHAR(36) NOT NULL,
    FOLDER_PATH VARCHAR(500) NOT NULL,  -- e.g., "/Engineering/Documentation"
    FOLDER_ID_GOOGLE VARCHAR(255),  -- Google Drive folder ID (optional)
    CREATED_BY VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    UNIQUE(ORG_ID, FOLDER_PATH)
)
CLUSTER BY (ORG_ID, FOLDER_PATH);

-- Add FOLDER_PATH column to DOCUMENTS table to cache folder paths
ALTER TABLE THIRDEYE_DEV.PUBLIC.DOCUMENTS 
ADD COLUMN IF NOT EXISTS FOLDER_PATH VARCHAR(500);

-- Create index on DOCUMENTS.FOLDER_PATH for faster lookups
-- Note: Snowflake uses CLUSTER BY instead of indexes, but we can add it to CLUSTER BY
-- The existing CLUSTER BY (ORG_ID, DOC_ID) should be sufficient

-- Verify table creation
SELECT 'WHITELISTED_FOLDERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT 
FROM THIRDEYE_DEV.PUBLIC.WHITELISTED_FOLDERS
UNION ALL
SELECT 'DOCUMENTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT 
FROM THIRDEYE_DEV.PUBLIC.DOCUMENTS;
