-- Add tables for storing agent results
-- Run this in Snowflake to enable agent result storage
-- Date: 2025-02-08

USE WAREHOUSE COMPUTE_WH;
USE DATABASE THIRDEYE_DEV;
USE SCHEMA PUBLIC;

-- Persona Cards Table
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.PERSONA_CARDS (
    PERSONA_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    PERSONA_CARD VARIANT NOT NULL,  -- JSON: expertiseLevels, learningStyle, etc.
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_CURRENT BOOLEAN DEFAULT TRUE
)
CLUSTER BY (USER_ID, CREATED_AT);

-- Gap Hypotheses Table
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.GAP_HYPOTHESES (
    HYPOTHESIS_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36),
    ANCHOR_ID VARCHAR(255),
    DOC_ID VARCHAR(500),
    HYPOTHESES VARIANT NOT NULL,  -- JSON: candidates, winning_hypothesis, etc.
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (USER_ID, CREATED_AT);

-- Explanations Table
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.EXPLANATIONS (
    EXPLANATION_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36),
    ANCHOR_ID VARCHAR(255),
    DOC_ID VARCHAR(500),
    HYPOTHESIS_ID VARCHAR(36),  -- Reference to GAP_HYPOTHESES
    EXPLANATION_DATA VARIANT NOT NULL,  -- JSON: instant_hud, deep_dive, action_cards
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (USER_ID, CREATED_AT);

-- Document Suggestions Table (for Agent 6.0)
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.DOCUMENT_SUGGESTIONS (
    SUGGESTION_ID VARCHAR(36) PRIMARY KEY,
    DOC_ID VARCHAR(500) NOT NULL,
    ORG_ID VARCHAR(36),
    ANCHOR_ID VARCHAR(255),
    HOTSPOT_ID VARCHAR(255),
    ORIGINAL_TEXT TEXT,
    SUGGESTED_TEXT TEXT,
    REASONING TEXT,
    CONFIDENCE FLOAT,
    CHANGES_MADE VARIANT,  -- JSON array
    STATUS VARCHAR(20) DEFAULT 'pending',  -- pending, accepted, rejected, applied
    CREATED_BY VARCHAR(36),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (DOC_ID, CREATED_AT);

-- Agent Execution Log (for tracking agent runs)
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.AGENT_EXECUTIONS (
    EXECUTION_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36),
    AGENT_ID VARCHAR(10) NOT NULL,  -- "0.0", "1.0", "2.0", etc.
    INPUT_DATA VARIANT,  -- JSON input
    OUTPUT_DATA VARIANT,  -- JSON output
    STATUS VARCHAR(20) DEFAULT 'running',  -- running, completed, failed
    ERROR_MESSAGE TEXT,
    EXECUTION_TIME_MS INTEGER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ
)
CLUSTER BY (USER_ID, CREATED_AT);

-- Verify table creation
SELECT 'PERSONA_CARDS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT 
FROM THIRDEYE_DEV.PUBLIC.PERSONA_CARDS
UNION ALL
SELECT 'GAP_HYPOTHESES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT 
FROM THIRDEYE_DEV.PUBLIC.GAP_HYPOTHESES
UNION ALL
SELECT 'EXPLANATIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT 
FROM THIRDEYE_DEV.PUBLIC.EXPLANATIONS
UNION ALL
SELECT 'DOCUMENT_SUGGESTIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT 
FROM THIRDEYE_DEV.PUBLIC.DOCUMENT_SUGGESTIONS
UNION ALL
SELECT 'AGENT_EXECUTIONS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT 
FROM THIRDEYE_DEV.PUBLIC.AGENT_EXECUTIONS;
