-- ThirdEye Snowflake Database Schema
-- Run this script to create all tables with proper clustering keys and indexes
-- Matches BACKEND_INTEGRATION_GUIDE.md specifications

-- Create schemas
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS AUDIT;

-- Users Table
CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
    USER_ID VARCHAR(36) PRIMARY KEY,
    GOOGLE_SUB VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    PICTURE_URL VARCHAR(500),
    ACCOUNT_TYPE VARCHAR(20) NOT NULL,
    HAS_ENTERPRISE_ACCESS BOOLEAN DEFAULT FALSE,
    PERSONA_CARD VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_LOGIN TIMESTAMP_NTZ
)
CLUSTER BY (USER_ID);

CREATE INDEX IF NOT EXISTS IDX_USERS_GOOGLE_SUB ON PUBLIC.USERS(GOOGLE_SUB);
CREATE INDEX IF NOT EXISTS IDX_USERS_EMAIL ON PUBLIC.USERS(EMAIL);

-- Sessions Table
CREATE TABLE IF NOT EXISTS PUBLIC.SESSIONS (
    SESSION_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL REFERENCES PUBLIC.USERS(USER_ID),
    DOC_ID VARCHAR(500),
    DOC_TITLE VARCHAR(500),
    DOC_TYPE VARCHAR(50),
    TITLE VARCHAR(500),
    STARTED_AT TIMESTAMP_NTZ NOT NULL,
    ENDED_AT TIMESTAMP_NTZ,
    DURATION_SECONDS INTEGER,
    CONCEPTS_COUNT INTEGER DEFAULT 0,
    TRIGGERS VARIANT,
    GAP_LABELS VARIANT,
    IS_COMPLETE BOOLEAN DEFAULT FALSE,
    SUMMARY TEXT,
    METADATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (USER_ID, STARTED_AT);

CREATE INDEX IF NOT EXISTS IDX_SESSIONS_USER_START ON PUBLIC.SESSIONS(USER_ID, STARTED_AT DESC);
CREATE INDEX IF NOT EXISTS IDX_SESSIONS_DOC ON PUBLIC.SESSIONS(DOC_ID);

-- Notebook Entries Table
CREATE TABLE IF NOT EXISTS PUBLIC.NOTEBOOK_ENTRIES (
    ENTRY_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL REFERENCES PUBLIC.USERS(USER_ID),
    SESSION_ID VARCHAR(36) REFERENCES PUBLIC.SESSIONS(SESSION_ID),
    TITLE VARCHAR(500) NOT NULL,
    CONTENT TEXT,
    SNIPPET VARCHAR(1000),
    PREVIEW VARCHAR(2000),
    TAGS VARIANT,
    RELATED_ENTRIES VARIANT,
    DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (USER_ID, DATE);

CREATE INDEX IF NOT EXISTS IDX_NOTEBOOK_USER_DATE ON PUBLIC.NOTEBOOK_ENTRIES(USER_ID, DATE DESC);
CREATE INDEX IF NOT EXISTS IDX_NOTEBOOK_SESSION ON PUBLIC.NOTEBOOK_ENTRIES(SESSION_ID);

-- Organizations Table
CREATE TABLE IF NOT EXISTS PUBLIC.ORGANIZATIONS (
    ORG_ID VARCHAR(36) PRIMARY KEY,
    ORG_NAME VARCHAR(255) NOT NULL,
    ADMIN_EMAIL VARCHAR(255) NOT NULL,
    ADMIN_USER_ID VARCHAR(36) REFERENCES PUBLIC.USERS(USER_ID),
    DRIVE_SOURCES VARIANT,  -- JSON array of Google Drive sources
    SETTINGS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ORG_ID);

-- Organization Memberships Table
CREATE TABLE IF NOT EXISTS PUBLIC.ORG_MEMBERSHIPS (
    MEMBERSHIP_ID VARCHAR(36) PRIMARY KEY,
    ORG_ID VARCHAR(36) NOT NULL REFERENCES PUBLIC.ORGANIZATIONS(ORG_ID),
    USER_ID VARCHAR(36) NOT NULL REFERENCES PUBLIC.USERS(USER_ID),
    ROLE VARCHAR(20) NOT NULL DEFAULT 'member',  -- 'admin' | 'member'
    JOINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE(ORG_ID, USER_ID)
)
CLUSTER BY (ORG_ID, USER_ID);

CREATE INDEX IF NOT EXISTS IDX_ORG_MEMBERSHIPS_ORG ON PUBLIC.ORG_MEMBERSHIPS(ORG_ID);
CREATE INDEX IF NOT EXISTS IDX_ORG_MEMBERSHIPS_USER ON PUBLIC.ORG_MEMBERSHIPS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_ORG_MEMBERSHIPS_ROLE ON PUBLIC.ORG_MEMBERSHIPS(ORG_ID, ROLE);

-- Documents Table
CREATE TABLE IF NOT EXISTS PUBLIC.DOCUMENTS (
    DOC_ID VARCHAR(500) PRIMARY KEY,
    ORG_ID VARCHAR(36) REFERENCES PUBLIC.ORGANIZATIONS(ORG_ID),
    TITLE VARCHAR(500) NOT NULL,
    GOOGLE_DOC VARIANT,
    CONFUSION_DENSITY FLOAT,
    TOTAL_TRIGGERS INTEGER DEFAULT 0,
    USERS_AFFECTED INTEGER DEFAULT 0,
    CONTENT TEXT,
    HOTSPOTS VARIANT,
    LAST_ANALYZED TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ORG_ID, DOC_ID);

CREATE INDEX IF NOT EXISTS IDX_DOCS_ORG ON PUBLIC.DOCUMENTS(ORG_ID);
CREATE INDEX IF NOT EXISTS IDX_DOCS_CONFUSION ON PUBLIC.DOCUMENTS(CONFUSION_DENSITY DESC);

-- Tracked Assets Table (general asset tracking for documents, GitHub repos, etc.)
CREATE TABLE IF NOT EXISTS PUBLIC.TRACKED_ASSETS (
    ASSET_ID VARCHAR(500) PRIMARY KEY,
    ORG_ID VARCHAR(36) REFERENCES PUBLIC.ORGANIZATIONS(ORG_ID),
    ASSET_TYPE VARCHAR(50) NOT NULL,  -- 'GOOGLE_DOC', 'GITHUB', 'NOTION', 'CONFLUENCE', etc.
    TITLE VARCHAR(500) NOT NULL,
    GOOGLE_DOC VARIANT,
    CONFUSION_DENSITY FLOAT,
    TOTAL_TRIGGERS INTEGER DEFAULT 0,
    USERS_AFFECTED INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ORG_ID, ASSET_TYPE);

CREATE INDEX IF NOT EXISTS IDX_TRACKED_ASSETS_TYPE ON PUBLIC.TRACKED_ASSETS(ASSET_TYPE);
CREATE INDEX IF NOT EXISTS IDX_TRACKED_ASSETS_ORG ON PUBLIC.TRACKED_ASSETS(ORG_ID);
CREATE INDEX IF NOT EXISTS IDX_TRACKED_ASSETS_CONFUSION ON PUBLIC.TRACKED_ASSETS(CONFUSION_DENSITY DESC);

-- Suggestions Table
CREATE TABLE IF NOT EXISTS PUBLIC.SUGGESTIONS (
    SUGGESTION_ID VARCHAR(36) PRIMARY KEY,
    DOC_ID VARCHAR(500) NOT NULL REFERENCES PUBLIC.DOCUMENTS(DOC_ID),
    ORG_ID VARCHAR(36) REFERENCES PUBLIC.ORGANIZATIONS(ORG_ID),
    HOTSPOT_ID VARCHAR(36),
    ORIGINAL_TEXT TEXT NOT NULL,
    SUGGESTED_TEXT TEXT NOT NULL,
    CONFIDENCE FLOAT,
    REASONING TEXT,
    CONFUSION_TYPE VARCHAR(50),
    DIAGNOSIS TEXT,
    ACTIONS VARIANT,
    GOOGLE_DOC_RANGE VARIANT,
    STATUS VARCHAR(20) DEFAULT 'pending',
    APPLIED_AT TIMESTAMP_NTZ,
    APPLIED_BY VARCHAR(36),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (DOC_ID, CREATED_AT);

CREATE INDEX IF NOT EXISTS IDX_SUGGESTIONS_DOC ON PUBLIC.SUGGESTIONS(DOC_ID, STATUS);
CREATE INDEX IF NOT EXISTS IDX_SUGGESTIONS_ORG ON PUBLIC.SUGGESTIONS(ORG_ID);

-- Interactions Table (for Agent 5.0 Memory Vault)
CREATE TABLE IF NOT EXISTS PUBLIC.INTERACTIONS (
    INTERACTION_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL REFERENCES PUBLIC.USERS(USER_ID),
    SESSION_ID VARCHAR(36) REFERENCES PUBLIC.SESSIONS(SESSION_ID),
    DOC_ID VARCHAR(500),
    ANCHOR_ID VARCHAR(255),
    CONTENT TEXT,
    GAP_HYPOTHESIS VARIANT,
    EXPLANATION_GIVEN VARIANT,
    USER_FEEDBACK VARCHAR(50),
    READING_STATE VARCHAR(20),
    DWELL_TIME_MS INTEGER,
    CONCEPTS VARIANT,
    TELEMETRY VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (USER_ID, CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS IDX_INTERACTIONS_USER_DATE ON PUBLIC.INTERACTIONS(USER_ID, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IDX_INTERACTIONS_SESSION ON PUBLIC.INTERACTIONS(SESSION_ID);

-- Analytics Tables

-- Time Saved Aggregates
CREATE TABLE IF NOT EXISTS ANALYTICS.TIME_SAVED_DAILY (
    USER_ID VARCHAR(36),
    DATE DATE,
    TOTAL_HOURS FLOAT,
    THIS_WEEK_HOURS FLOAT,
    THIS_MONTH_HOURS FLOAT,
    BREAKDOWN VARIANT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ID, DATE)
)
CLUSTER BY (USER_ID, DATE);

-- Enterprise KPIs
CREATE TABLE IF NOT EXISTS ANALYTICS.ENTERPRISE_KPIS (
    ORG_ID VARCHAR(36),
    DATE DATE,
    TIME_RECLAIMED FLOAT,
    TOTAL_TRIGGERS INTEGER,
    TOP_DOCUMENTS VARIANT,
    EFFICIENCY_DATA VARIANT,
    CURRENT_EFFICIENCY FLOAT,
    PREDICTED_EFFICIENCY FLOAT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ORG_ID, DATE)
)
CLUSTER BY (ORG_ID, DATE);
