-- Google Docs Enterprise Integration (v1)
-- Run with Snowflake role that can create objects in THIRDEYE_DEV.PUBLIC

CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.AOI_MAP (
    DOC_ID STRING,
    ORG_ID STRING,
    AOI_KEY STRING,
    HEADING_PATH VARIANT,
    PARAGRAPH_INDEX NUMBER,
    START_INDEX NUMBER,
    END_INDEX NUMBER,
    SNIPPET STRING,
    ANCHOR VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DOC_ID, AOI_KEY)
);

CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.ATTENTION_EVENTS (
    EVENT_ID STRING,
    ORG_ID STRING,
    DOC_ID STRING,
    USER_ID STRING,
    SESSION_ID STRING,
    AOI_KEY STRING,
    AOI_ID STRING,
    STATE STRING,
    DWELL_MS NUMBER,
    REGRESSIONS NUMBER,
    TS TIMESTAMP_NTZ,
    BBOX VARIANT,
    CONTEXT VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_ID)
);

CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.AOI_AGGREGATES (
    AGG_ID STRING,
    ORG_ID STRING,
    DOC_ID STRING,
    AOI_KEY STRING,
    WINDOW_START TIMESTAMP_NTZ,
    WINDOW_END TIMESTAMP_NTZ,
    METRICS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (AGG_ID)
);

CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.DOC_SUGGESTIONS (
    SUGGESTION_ID STRING,
    ORG_ID STRING,
    DOC_ID STRING,
    AOI_KEY STRING,
    TITLE STRING,
    ORIGINAL_TEXT STRING,
    PROPOSED_TEXT STRING,
    RATIONALE STRING,
    RISK_FLAGS VARIANT,
    ANCHOR VARIANT,
    STATUS STRING,
    SOURCE STRING,
    MANAGER_NOTE STRING,
    APPLIED_AT TIMESTAMP_NTZ,
    APPLIED_BY STRING,
    BACKUP_TEXT STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUGGESTION_ID)
);

CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.GOOGLE_USER_TOKENS (
    USER_ID STRING,
    GOOGLE_ACCESS_TOKEN STRING,
    REFRESH_TOKEN STRING,
    SCOPE STRING,
    EXPIRES_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ID)
);
