-- Create DOCUMENTS and INTERACTIONS tables that the code expects
-- Run this in Snowflake NOW to fix the error

USE WAREHOUSE COMPUTE_WH;
USE DATABASE THIRDEYE_DEV;
USE SCHEMA PUBLIC;

-- Create DOCUMENTS table (no foreign key to avoid FK errors)
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.DOCUMENTS (
    DOC_ID VARCHAR(500) PRIMARY KEY,
    ORG_ID VARCHAR(36),
    TITLE VARCHAR(500) NOT NULL,
    GOOGLE_DOC VARIANT,
    CONFUSION_DENSITY FLOAT,
    TOTAL_TRIGGERS INTEGER DEFAULT 0,
    USERS_AFFECTED INTEGER DEFAULT 0,
    CONTENT TEXT,
    HOTSPOTS VARIANT,
    LAST_ANALYZED TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ORG_ID, DOC_ID);

-- Create INTERACTIONS table (no foreign keys to avoid FK errors)
-- Note: Foreign key constraints removed - application code will enforce referential integrity
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.INTERACTIONS (
    INTERACTION_ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36),
    DOC_ID VARCHAR(500),
    ANCHOR_ID VARCHAR(255),
    CONTENT TEXT,
    GAP_HYPOTHESIS VARIANT,
    EXPLANATION_GIVEN VARIANT,
    USER_FEEDBACK VARCHAR(50),
    READING_STATE VARCHAR(20),
    DWELL_TIME_MS INTEGER,
    CONCEPTS VARIANT,
    TELEMETRY VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (USER_ID, CREATED_AT);

-- Verify they were created
SELECT TABLE_NAME 
FROM THIRDEYE_DEV.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'PUBLIC'
  AND TABLE_NAME IN ('DOCUMENTS', 'INTERACTIONS')
ORDER BY TABLE_NAME;
