-- ThirdEye Snowflake Schema Update
-- Run this script to add missing tables to existing database
-- Date: 2025-01-27

-- Add DRIVE_SOURCES column to ORGANIZATIONS if it doesn't exist
-- Note: Snowflake doesn't support IF NOT EXISTS for ALTER TABLE ADD COLUMN
-- Run this manually if needed:
-- ALTER TABLE THIRDEYE_DEV.PUBLIC.ORGANIZATIONS ADD COLUMN IF NOT EXISTS DRIVE_SOURCES VARIANT;

-- Tracked Assets Table (general asset tracking for documents, GitHub repos, etc.)
-- Note: Snowflake doesn't support CREATE INDEX on standard tables
-- The CLUSTER BY clause provides automatic optimization instead
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.TRACKED_ASSETS (
    ASSET_ID VARCHAR(500) PRIMARY KEY,
    ORG_ID VARCHAR(36) REFERENCES THIRDEYE_DEV.PUBLIC.ORGANIZATIONS(ORG_ID),
    ASSET_TYPE VARCHAR(50) NOT NULL,  -- 'GOOGLE_DOC', 'GITHUB', 'NOTION', 'CONFLUENCE', etc.
    TITLE VARCHAR(500) NOT NULL,
    GOOGLE_DOC VARIANT,
    CONFUSION_DENSITY FLOAT,
    TOTAL_TRIGGERS INTEGER DEFAULT 0,
    USERS_AFFECTED INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ORG_ID, ASSET_TYPE);

-- Organization Memberships Table
-- Note: Snowflake doesn't support CREATE INDEX on standard tables
-- The CLUSTER BY clause provides automatic optimization instead
CREATE TABLE IF NOT EXISTS THIRDEYE_DEV.PUBLIC.ORG_MEMBERSHIPS (
    MEMBERSHIP_ID VARCHAR(36) PRIMARY KEY,
    ORG_ID VARCHAR(36) NOT NULL REFERENCES THIRDEYE_DEV.PUBLIC.ORGANIZATIONS(ORG_ID),
    USER_ID VARCHAR(36) NOT NULL REFERENCES THIRDEYE_DEV.PUBLIC.USERS(USER_ID),
    ROLE VARCHAR(20) NOT NULL DEFAULT 'member',  -- 'admin' | 'member'
    JOINED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE(ORG_ID, USER_ID)
)
CLUSTER BY (ORG_ID, USER_ID);

-- Verify tables were created
SELECT 'TRACKED_ASSETS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM THIRDEYE_DEV.PUBLIC.TRACKED_ASSETS
UNION ALL
SELECT 'ORG_MEMBERSHIPS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM THIRDEYE_DEV.PUBLIC.ORG_MEMBERSHIPS;
